version: '3.5'
services:
  librarymicroservice:
    container_name: librarymicroservice
    restart: always
    build: ~/documents/training/angular/librarymicroservice
    image: librarymicroservice
    ports:
      - '5010:3000'
    environment:
      - NODE_ENV=docker
    command: npm run start
    depends_on: [mongo]

  mongo:
    container_name: mongo
    image: mongo@sha256:f4ff7bb4291eb5d3f530a726fc524ba8e4318d652e64f2d58560ff87d083a84c
    ports:
      - '8084:27017'
    volumes:
      - ~/mongodata:/data/db